const detail = [
  {
    name: "2018 Komatsu WA380-8 Wheel Loader",
    date: "Thu, Aug 8, GMT+3",
    usage: "1500hrs",
    thumbnails: ["5 cu yd Bucket • 191 HP", "Tier 4 Final Engine"],
    location: "Vancouver, BC, CAN",
    lot: 765322,
    image: `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
  },
  {
    name: "2020 Bobcat E85 Compact Excavator",
    date: "Tue, Jul 27, GMT+2",
    usage: "876hrs",
    thumbnails: ["8.5 Ton • Rubber Tracks", "64.7 HP Diesel Engine"],
    location: "Edmonton, AB, CAN",
    lot: 973212,
    image: `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
  },
  {
    name: "2019 Volvo EC220EL Hydraulic Excavator",
    date: "Fri, Sep 10, GMT+3",
    usage: "2300hrs",
    thumbnails: ["51,000 lbs Operating Weight", "167 HP Tier 4 Final Engine"],
    location: "Halifax, NS, CAN",
    lot: 135874,
    image: `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
  },
  {
    name: "2018 Komatsu WA380-8 Wheel Loader",
    date: "Thu, Aug 8, GMT+3",
    usage: "1500hrs",
    thumbnails: ["5 cu yd Bucket • 191 HP", "Tier 4 Final Engine"],
    location: "Vancouver, BC, CAN",
    lot: 765322,
    image: `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
  },
  {
    name: "2020 Bobcat E85 Compact Excavator",
    date: "Tue, Jul 27, GMT+2",
    usage: "876hrs",
    thumbnails: ["8.5 Ton • Rubber Tracks", "64.7 HP Diesel Engine"],
    location: "Edmonton, AB, CAN",
    lot: 973212,
    image: `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
  },
  {
    name: "2019 Volvo EC220EL Hydraulic Excavator",
    date: "Fri, Sep 10, GMT+3",
    usage: "2300hrs",
    thumbnails: ["51,000 lbs Operating Weight", "167 HP Tier 4 Final Engine"],
    location: "Halifax, NS, CAN",
    lot: 135874,
    image: `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
  },
  {
    name: "2014 Hitachi ZX470LC-5 Excavator",
    date: "Sun, Dec 5, GMT+3",
    usage: "4589hrs",
    thumbnails: ["52,500 lbs Operating Weight", "362 HP • Long Reach Boom"],
    location: "Montreal, QC, CAN",
    lot: 481290,
    image: `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
  },
  {
    name: "2014 Hitachi ZX470LC-5 Excavator",
    date: "Sun, Dec 5, GMT+3",
    usage: "4589hrs",
    thumbnails: ["52,500 lbs Operating Weight", "362 HP • Long Reach Boom"],
    location: "Montreal, QC, CAN",
    lot: 481290,
    image: `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
  },
  {
    name: "2021 JLG 450AJ Boom Lift",
    date: "Sat, Jun 26, GMT+1",
    usage: "670hrs",
    thumbnails: ["45 ft Platform Height", "4x4 • Diesel Engine"],
    location: "Regina, SK, CAN",
    lot: 318947,
    image: `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
  },
  {
    name: "2018 Genie GTH-1056 Telehandler",
    date: "Wed, May 19, GMT+3",
    usage: "1234hrs",
    thumbnails: ["10,000 lb Max Lift", "56 ft Reach • 4x4"],
    location: "Ottawa, ON, CAN",
    lot: 674342,
    image: `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
  },
  {
    name: "2017 Case 580N Backhoe Loader",
    date: "Mon, Apr 12, GMT+2",
    usage: "3650hrs",
    thumbnails: ["90 HP Engine • 4WD", "Extended Dipper Stick"],
    location: "Winnipeg, MB, CAN",
    lot: 412875,
    image: `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
  },
  {
    name: "2019 Caterpillar D6T Dozer",
    date: "Tue, Feb 15, GMT+1",
    usage: "2100hrs",
    thumbnails: ["200 HP Tier 4 Final Engine", "Full Cab • LGP Tracks"],
    location: "Quebec City, QC, CAN",
    lot: 763901,
    image: `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
  },
];

export default detail;
