const ItemsList = [
  {
    flag: "bi bi-flag",
    name: "Ontario Regional Events CAN",
    date: "Sep 10",
    region: "ON",
    format: "live auction",
    bid: "Accepting bid",
    location: [
      { city: "Bolton" },
      { city: "Caledon East" },
      { city: "Thunder Bay" },
    ],
    found: ["onsite", "online"],
    stock: 355,
    images: [
      `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader3.jpg`,
    ],
  },
  {
    flag: "bi bi-flag",
    name: "Quebec Regional Conference CAN",
    date: "Oct 15",
    region: "QC",
    format: "timed auction",
    bid: "Accepting bid",
    location: [{ city: "Montreal" }, { city: "Quebec City" }],
    found: ["onsite"],
    stock: 210,
    images: [
      `${import.meta.env.BASE_URL}/images/graders/grader4.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader3.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
    ],
  },
  {
    flag: "bi bi-flag",
    name: "Alberta Construction Summit CAN",
    date: "Nov 12",
    region: "AB",
    format: "live auction",
    location: [{ city: "Calgary" }, { city: "Edmonton" }],
    found: ["online"],
    stock: 150,
    images: [
      `${import.meta.env.BASE_URL}/images/graders/grader3.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader4.jpg`,
    ],
  },
  {
    flag: "bi bi-flag",
    name: "British Columbia Tech Expo CAN",
    date: "Dec 05",
    region: "BC",
    format: "timed auction",
    bid: "Accepting bid",
    location: [{ city: "Vancouver" }, { city: "Victoria" }],
    found: ["onsite", "online"],
    stock: 500,
    images: [
      `${import.meta.env.BASE_URL}/images/graders/grader3.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader4.jpg`,
    ],
  },
  {
    flag: "bi bi-flag",
    name: "Nova Scotia Maritime Expo CAN",
    date: "Jan 20",
    region: "NS",
    format: "live auction",
    location: [{ city: "Halifax" }, { city: "Dartmouth" }],
    found: ["onsite"],
    stock: 320,
    images: [
      `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader3.jpg`,
    ],
  },
  {
    flag: "bi bi-flag",
    name: "Manitoba Agricultural Fair CAN",
    date: "Feb 17",
    region: "MB",
    format: "timed auction",
    bid: "Accepting bid",
    location: [{ city: "Winnipeg" }, { city: "Brandon" }],
    found: ["onsite", "online"],
    stock: 280,
    images: [
      `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader3.jpg`,
    ],
  },
  {
    flag: "bi bi-flag",
    name: "Newfoundland Fisheries Conference CAN",
    date: "Mar 25",
    region: "NL",
    format: "live auction",
    location: [{ city: "St. John's" }],
    found: ["online"],
    stock: 100,
    images: [
      `${import.meta.env.BASE_URL}/images/graders/grader3.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader4.jpg`,
    ],
  },
  {
    flag: "bi bi-flag",
    name: "Saskatchewan Farming Expo CAN",
    date: "Apr 30",
    region: "SK",
    format: "timed auction",
    location: [{ city: "Saskatoon" }, { city: "Regina" }],
    found: ["onsite"],
    stock: 250,
    images: [
      `${import.meta.env.BASE_URL}/images/graders/grader4.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader3.jpg`,
    ],
  },
  {
    flag: "bi bi-flag",
    name: "Prince Edward Island Tourism Fair CAN",
    date: "May 22",
    region: "PE",
    format: "live auction",
    bid: "Accepting bid",
    location: [{ city: "Charlottetown" }],
    found: ["onsite", "online"],
    stock: 180,
    images: [
      `${import.meta.env.BASE_URL}/images/graders/grader3.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader4.jpg`,
    ],
  },
  {
    flag: "bi bi-flag",
    name: "New Brunswick Business Forum CAN",
    date: "Jun 18",
    region: "NB",
    format: "timed auction",
    location: [{ city: "Moncton" }, { city: "Saint John" }],
    found: ["onsite"],
    stock: 290,
    images: [
      `${import.meta.env.BASE_URL}/images/graders/grader2.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader3.jpg`,
      `${import.meta.env.BASE_URL}/images/graders/grader1.jpg`,
    ],
  },
];

export default ItemsList;
